"""
Aquí guardamos todas las constantes para encontrarlas más fácilmente,
si es que necesitamos editar los valores
"""
#----------GENERAL----------#
#TANAÑO DE PANTALLA
SCR_WIDTH = 960
SCR_HEIGHT = 540

#COLORES
COLOR_WHITE = (255, 255, 255) 
COLOR_RED = (255, 0, 0) 
COLOR_BLUE = (0, 204, 255) 
COLOR_BLACK = (0 ,0 ,0)
COLOR_YELLOW = (255 ,195 ,0)
COLOR_GRAY = (150, 150, 150)
COLOR_GREEN = (70, 255, 70)
COLOR_DARK_GRAY = (44, 44, 44)

#FPS
MAX_FPS = 60



#----------MENU PRINCIPAL----------#
#POSICIÓN DEL TEXTO DE TITULO
TITLE_MENU_X = 280
TITLE_MENU_Y = 100

#TAMAÑO DE BOTONES
BUTTON_WIDTH = 180
BUTTON_HEIGHT = 50

#POSICIÓN DE BOTONES DE MENÚ PRINCIPAL
START_BUTTON_TOP = SCR_HEIGHT / 2 - 10
OPTIONS_BUTTON_TOP = SCR_HEIGHT / 2 + 50
EXIT_BUTTON_TOP = SCR_HEIGHT / 2 + 110

BUTTON_LEFT = SCR_WIDTH / 2 - 100


#----------JUEGO----------#
#ESTADÍSTICAS
TEXT_STADISTICS_Y = 490
TEXT_STADISTICS_X = 140

#TAMAÑO DE LOS BOTONES DE LAS OPCIONES DEL EVENTO
BUTTON_OPTION_WIDTH = 500
BUTTON_OPTION_HEIGHT = 50

TITLE_EVENT_TEXT_X = 280
TITLE_EVENT_TEXT_Y = 50

DESCRIPTION_EVENT_TEXT_X = 280
DESCRIPTION_EVENT_TEXT_Y = TITLE_EVENT_TEXT_Y + 40
DESCRIPTION_EVENT_TEXT_WIDTH = 500
DESCRIPTION_EVENT_TEXT_HEIGHT = 300


#----------IMÁGENES----------#
#JUGADOR (posición y tamaño)
PLAYER_X = 10
PLAYER_Y = SCR_HEIGHT-150
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 130

#CORAZONES DE SALUD
HEART_WIDTH = 50
HEART_HEIGHT = 50
HEART_FIRST_X = 120
HEART_FIRST_Y  = 380

#ESTADÍSTICAS DEL JUGADOR
STADISTIC_WIDTH = 50
STADISTIC_HEIGHT = 50
STADISTIC_FIRST_X = 120
STADISTIC_FIRST_Y = 430

#EVENTO
EVENT_IMAGE_WIDTH = 250
EVENT_IMAGE_HEIGHT = 260
EVENT_IMAGE_X = 20
EVENT_IMAGE_Y = 50

#OPCIONES DEL EVENTO
EVENT_OPTION_IMAGE_WIDTH = 40
EVENT_OPTION_IMAGE_HEIGHT = 40
EVENT_OPTION_IMAGE_FIRST_X = 280
EVENT_OPTION_IMAGE_FIRST_Y = 200



