"""
Aquí guardamos todas las constantes para encontrarlas más fácilmente,
si es que necesitamos editar los valores
"""
#----------INTERFAZ DE USUARIO----------#
#TANAÑO DE PANTALLA
SCR_WIDTH = 960
SCR_HEIGHT = 540

#COLORES
COLOR_WHITE = (255, 255, 255) 
COLOR_RED = (255, 0, 0) 
COLOR_BLUE = (0, 204, 255) 
COLOR_BLACK = (0 ,0 ,0)
COLOR_YELLOW = (255 ,195 ,0)
COLOR_GRAY = (150, 150, 150)
COLOR_GREEN = (70, 255, 70)

#FPS
MAX_FPS = 60

#POSICIÓN DEL TEXTO DE TITULO
TITLE_MENU_X = 280
TITLE_MENU_Y = 100

#POSICIÓN DE BOTONES DE MENÚ PRINCIPAL
START_BUTTON_TOP = SCR_HEIGHT / 2 - 10
OPTIONS_BUTTON_TOP = SCR_HEIGHT / 2 + 50
EXIT_BUTTON_TOP = SCR_HEIGHT / 2 + 110

BUTTON_LEFT = SCR_WIDTH / 2 - 100

#TAMAÑO DE BOTONES
BUTTON_WIDTH = 170
BUTTON_HEIGHT = 50


#----------JUEGO----------#
### IMAGENES ###
#JUGADOR (posición y tamaño)
PLAYER_X = 10
PLAYER_Y = SCR_HEIGHT-150
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 130

#CORAZONES DE SALUD
HEART_WIDTH = 50
HEART_HEIGHT = 50
HEART_FIRST_X = 120
HEART_FIRST_Y  = 380

#ESTADÍSTICAS DEL JUGADOR
STADISTIC_WIDTH = 50
STADISTIC_HEIGHT = 50
STADISTIC_FIRST_X = 120
STADISTIC_FIRST_Y = 430

### POSICIÓN TEXTO ###
#ESTADÍSTICAS
TEXT_STADISTICS_Y = 490
TEXT_STADISTICS_X = 140

